spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpatest
    username: jpatester
    password: jpatest
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace